version: '3.8'
services:
  # API Gateway (Nginx)
  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - product-service
      - order-service

  # Authentication Microservice
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:80"
    environment:
      DB_HOST: db
      DB_DATABASE: auth_db
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - db

  # Product Management Microservice
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8082:80"
    environment:
      DB_HOST: db
      DB_DATABASE: product_db
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - db

  # Order Processing Microservice
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8083:80"
    environment:
      DB_HOST: db
      DB_DATABASE: order_db
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - db

  # MySQL Database
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: main_db
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
