version: '3.8'
services:
  # Nginx
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  #PHP
  app:
      build:
        dockerfile: ./php/Dockerfile
      volumes:
        - ./app:/var/www/html
      environment:
        MYSQL_HOST: db
        MYSQL_PORT: ${MYSQL_PORT}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_HOST: cache

  #MySql
  db:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  #Cache
  cache:
    image: redis:latest

volumes:
  dbdata: