version: '3.8'
services:
  # Nginx
  web:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  #PHP
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: app

  #MySql
  db:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: washi
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: main_db

volumes:
  dbdata: