version: '3.8'
services:
  # Nginx
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  #PHP
  app:
      build:
        dockerfile: ./php/Dockerfile
        target: "${BUILD_TARGET:-app}"
      volumes:
        - ./app:/var/www/html
        - ./php/config.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      environment:
        MYSQL_HOST: db
        MYSQL_PORT: ${MYSQL_PORT}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_HOST: cache
        XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      extra_hosts:
        # Ensure that host.docker.internal is correctly defined on Linux
        - host.docker.internal:host-gateway

  #MySql
  db:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  #Cache
  cache:
    image: redis:latest

volumes:
  dbdata: